version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    # Look for requirements files in the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: "monday"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "python"
    # Set version update strategy
    versioning-strategy: "increase-if-necessary"
    # Group updates together
    groups:
      dependencies:
        patterns:
          - "*"
    # Only allow minor and patch updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Set reviewers
    reviewers:
      - "dependabot"
    # Set commit message prefix
    commit-message:
      prefix: "pip"
      include: "scope"
    # Set target branch
    target-branch: "main"
    # Set rebase strategy
    rebase-strategy: "auto"
    # Set open pull request limit
    open-pull-requests-limit: 25 