services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: christopher
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
