name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: make install
      - run: make lint
      - run: make test