name: 'coverage'

on:
    pull_request:
        branches:
            - main
jobs:
  coverage:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: make install
      - run: make coverage
      - name: Get Coverage
        uses: orgoro/coverage@v3.2
        with:
            coverageFile: coverage.xml
            token: ${{ secrets.GITHUB_TOKEN }}
      - run: make lint